// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC815DNqvZSgvhpolrBmPq6l7tECvAhO70',
    appId: '1:824266710641:web:e08336b67142d2e5b785d0',
    messagingSenderId: '824266710641',
    projectId: 'fitstyle-f34d2',
    authDomain: 'fitstyle-f34d2.firebaseapp.com',
    storageBucket: 'fitstyle-f34d2.firebasestorage.app',
    measurementId: 'G-5F3L2S6WWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvCSSgTHUzPPLjyxUj184SGL7Lc79FgE',
    appId: '1:824266710641:android:6ed0d120d511dbb5b785d0',
    messagingSenderId: '824266710641',
    projectId: 'fitstyle-f34d2',
    storageBucket: 'fitstyle-f34d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMNUopcnQduznzJIefvm0mRtPbIcVPR8Y',
    appId: '1:824266710641:ios:8e935175b9856c61b785d0',
    messagingSenderId: '824266710641',
    projectId: 'fitstyle-f34d2',
    storageBucket: 'fitstyle-f34d2.firebasestorage.app',
    iosBundleId: 'com.example.fitstyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMNUopcnQduznzJIefvm0mRtPbIcVPR8Y',
    appId: '1:824266710641:ios:8e935175b9856c61b785d0',
    messagingSenderId: '824266710641',
    projectId: 'fitstyle-f34d2',
    storageBucket: 'fitstyle-f34d2.firebasestorage.app',
    iosBundleId: 'com.example.fitstyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC815DNqvZSgvhpolrBmPq6l7tECvAhO70',
    appId: '1:824266710641:web:0208bf054caba867b785d0',
    messagingSenderId: '824266710641',
    projectId: 'fitstyle-f34d2',
    authDomain: 'fitstyle-f34d2.firebaseapp.com',
    storageBucket: 'fitstyle-f34d2.firebasestorage.app',
    measurementId: 'G-6MWH1QS70Z',
  );
}
